### ISSUE TITLE
This line conflicts with something in the new update.

### ISSUE THREAD

**Issue by DrZhivago1** [tkkntkkn/natures-pretty-sweet#5]
https://github.com/tkkntkkn/natures-pretty-sweet/blob/e82dd642a45d447c5aa4df30916698f4c65ce2d8/Defs/Things/ThingDefs_Resources.xml#L277

Creates a double "smoothedThing"

**Comment by tkkntkkn** [comment]
Fixed w/ commit 3f93a3b
